import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";

// GET /api/communication/channels/department - Get or create user's department channel
export async function GET(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { 
        id: true, 
        department: true, 
        role: true,
        firstName: true,
        lastName: true,
        name: true
      },
    });

    if (!user || !user.department) {
      return NextResponse.json({ 
        error: "User department not found. Please contact HR to assign you to a department." 
      }, { status: 404 });
    }

    // Check if department team exists
    let team = await prisma.team.findFirst({
      where: { name: user.department },
    });

    // Create team if it doesn't exist
    if (!team) {
      team = await prisma.team.create({
        data: {
          name: user.department,
          description: `${user.department} Department Team`,
          color: "#0B874E",
          icon: "users",
          isActive: true,
        },
      });
    }

    // Check if department channel exists
    let channel = await prisma.chatChannel.findFirst({
      where: {
        type: 'DEPARTMENT',
        departmentId: team.id,
        isActive: true,
      },
      include: {
        members: {
          where: { leftAt: null },
          include: {
            user: {
              select: {
                id: true,
                name: true,
                firstName: true,
                lastName: true,
                avatar: true,
                role: true,
                department: true,
              },
            },
          },
        },
        messages: {
          take: 1,
          orderBy: { createdAt: 'desc' },
          include: {
            author: {
              select: {
                id: true,
                name: true,
                firstName: true,
                lastName: true,
                avatar: true,
              },
            },
          },
        },
        department: {
          select: {
            id: true,
            name: true,
            color: true,
          },
        },
      },
    });

    // Create department channel if it doesn't exist
    if (!channel) {
      channel = await prisma.chatChannel.create({
        data: {
          name: `${user.department} Department`,
          description: `Official communication channel for ${user.department} department`,
          type: 'DEPARTMENT',
          departmentId: team.id,
          isAutoGenerated: true,
          isActive: true,
          createdById: session.user.id,
        },
        include: {
          members: {
            where: { leftAt: null },
            include: {
              user: {
                select: {
                  id: true,
                  name: true,
                  firstName: true,
                  lastName: true,
                  avatar: true,
                  role: true,
                  department: true,
                },
              },
            },
          },
          messages: {
            take: 1,
            orderBy: { createdAt: 'desc' },
            include: {
              author: {
                select: {
                  id: true,
                  name: true,
                  firstName: true,
                  lastName: true,
                  avatar: true,
                },
              },
            },
          },
          department: {
            select: {
              id: true,
              name: true,
              color: true,
            },
          },
        },
      });

      // Add all department users to the channel
      const departmentUsers = await prisma.user.findMany({
        where: {
          department: user.department,
          status: 'ACTIVE',
        },
        select: { id: true },
      });

      if (departmentUsers.length > 0) {
        await prisma.chatMember.createMany({
          data: departmentUsers.map(u => ({
            channelId: channel.id,
            userId: u.id,
            role: ['SUPER_ADMIN', 'ADMIN', 'DIRECTOR', 'HR_OFFICER', 'TEAM_LEAD'].includes(user.role) ? 'ADMIN' : 'MEMBER',
          })),
          skipDuplicates: true,
        });

        // Send welcome message
        await prisma.chatMessage.create({
          data: {
            channelId: channel.id,
            authorId: session.user.id,
            content: `Welcome to the ${user.department} department chat! 🎉 This is where we collaborate, share updates, and stay connected as a team.`,
            messageType: 'SYSTEM',
          },
        });
      }
    } else {
      // Ensure current user is a member
      const existingMembership = await prisma.chatMember.findFirst({
        where: {
          channelId: channel.id,
          userId: session.user.id,
          leftAt: null,
        },
      });

      if (!existingMembership) {
        await prisma.chatMember.create({
          data: {
            channelId: channel.id,
            userId: session.user.id,
            role: ['SUPER_ADMIN', 'ADMIN', 'DIRECTOR', 'HR_OFFICER', 'TEAM_LEAD'].includes(user.role) ? 'ADMIN' : 'MEMBER',
          },
        });
      }
    }

    // Calculate unread count
    const member = channel.members.find(m => m.userId === session.user.id);
    const lastReadAt = member?.lastReadAt || new Date(0);

    const unreadCount = await prisma.chatMessage.count({
      where: {
        channelId: channel.id,
        createdAt: { gt: lastReadAt },
        authorId: { not: session.user.id },
        isDeleted: false,
      },
    });

    const channelWithUnread = {
      ...channel,
      unreadCount,
      lastMessage: channel.messages[0] || null,
    };

    return NextResponse.json({ channel: channelWithUnread });
  } catch (error) {
    console.error("Error getting/creating department channel:", error);
    return NextResponse.json(
      { error: "Failed to access department channel" },
      { status: 500 }
    );
  }
}