import { prisma } from "@/lib/db"
import { 
  createNewMemberAnnouncement,
  createAchievementAnnouncement,
  createProjectUpdateAnnouncement
} from "./communication"

/**
 * Sync service to integrate communication with other modules
 */

/**
 * Called when a new user is approved - creates welcome announcement and adds to department channels
 */
export async function onUserApproved(userId: string) {
  try {
    // Create welcome announcement
    await createNewMemberAnnouncement(userId)

    // Get user's department
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { department: true }
    })

    if (user?.department) {
      // Find department team
      const team = await prisma.team.findFirst({
        where: { name: user.department }
      })

      if (team) {
        // Add user to team
        await prisma.userTeam.upsert({
          where: {
            userId_teamId: {
              userId,
              teamId: team.id
            }
          },
          update: {},
          create: {
            userId,
            teamId: team.id,
            role: 'MEMBER'
          }
        })

        // Find department channel and add user
        const departmentChannel = await prisma.chatChannel.findFirst({
          where: {
            type: 'DEPARTMENT',
            departmentId: team.id,
            isActive: true
          }
        })

        if (departmentChannel) {
          await prisma.chatMember.upsert({
            where: {
              channelId_userId: {
                channelId: departmentChannel.id,
                userId
              }
            },
            update: { leftAt: null }, // Rejoin if previously left
            create: {
              channelId: departmentChannel.id,
              userId,
              role: 'MEMBER'
            }
          })
        }
      }
    }

    return { success: true }
  } catch (error) {
    console.error('Error in onUserApproved:', error)
    return { success: false, error: 'Failed to sync user approval' }
  }
}

/**
 * Called when a user receives a reward/badge
 */
export async function onUserRewarded(userId: string, badgeId: string, reason?: string) {
  try {
    await createAchievementAnnouncement(userId, badgeId, reason)
    return { success: true }
  } catch (error) {
    console.error('Error in onUserRewarded:', error)
    return { success: false, error: 'Failed to create achievement announcement' }
  }
}

/**
 * Called when a project status changes
 */
export async function onProjectStatusChange(projectId: string, oldStatus: string, newStatus: string) {
  try {
    let updateType: 'STARTED' | 'COMPLETED' | 'MILESTONE' | null = null

    if (oldStatus === 'PLANNING' && newStatus === 'ACTIVE') {
      updateType = 'STARTED'
    } else if (newStatus === 'COMPLETED') {
      updateType = 'COMPLETED'
    } else if (oldStatus !== newStatus) {
      updateType = 'MILESTONE'
    }

    if (updateType) {
      await createProjectUpdateAnnouncement(projectId, updateType)
    }

    return { success: true }
  } catch (error) {
    console.error('Error in onProjectStatusChange:', error)
    return { success: false, error: 'Failed to create project update' }
  }
}

/**
 * Called when a new team is created - creates department channel
 */
export async function onTeamCreated(teamId: string) {
  try {
    const team = await prisma.team.findUnique({
      where: { id: teamId },
      include: {
        members: {
          include: { user: true }
        }
      }
    })

    if (!team || team.members.length === 0) {
      return { success: false, error: 'Team not found or has no members' }
    }

    // Create department channel
    const channel = await prisma.chatChannel.create({
      data: {
        name: `${team.name} Team`,
        description: `Official channel for ${team.name} department`,
        type: 'DEPARTMENT',
        departmentId: team.id,
        isAutoGenerated: true,
        createdById: team.members[0].userId
      }
    })

    // Add all team members
    const memberData = team.members.map(member => ({
      channelId: channel.id,
      userId: member.userId,
      role: member.role === 'LEADER' ? 'ADMIN' as const : 'MEMBER' as const
    }))

    await prisma.chatMember.createMany({
      data: memberData
    })

    // Send welcome message
    await prisma.chatMessage.create({
      data: {
        channelId: channel.id,
        authorId: team.members[0].userId,
        content: `Welcome to the ${team.name} team channel! 🎉 This is your space for team discussions, updates, and collaboration.`,
        messageType: 'SYSTEM'
      }
    })

    return { success: true, channelId: channel.id }
  } catch (error) {
    console.error('Error in onTeamCreated:', error)
    return { success: false, error: 'Failed to create department channel' }
  }
}

/**
 * Called when a user joins a team - adds to department channel
 */
export async function onUserJoinedTeam(userId: string, teamId: string) {
  try {
    // Find department channel
    const departmentChannel = await prisma.chatChannel.findFirst({
      where: {
        type: 'DEPARTMENT',
        departmentId: teamId,
        isActive: true
      }
    })

    if (departmentChannel) {
      await prisma.chatMember.upsert({
        where: {
          channelId_userId: {
            channelId: departmentChannel.id,
            userId
          }
        },
        update: { leftAt: null },
        create: {
          channelId: departmentChannel.id,
          userId,
          role: 'MEMBER'
        }
      })
    }

    return { success: true }
  } catch (error) {
    console.error('Error in onUserJoinedTeam:', error)
    return { success: false, error: 'Failed to add user to department channel' }
  }
}

/**
 * Called when a user leaves a team - removes from department channel
 */
export async function onUserLeftTeam(userId: string, teamId: string) {
  try {
    // Find department channel
    const departmentChannel = await prisma.chatChannel.findFirst({
      where: {
        type: 'DEPARTMENT',
        departmentId: teamId,
        isActive: true
      }
    })

    if (departmentChannel) {
      await prisma.chatMember.updateMany({
        where: {
          channelId: departmentChannel.id,
          userId
        },
        data: { leftAt: new Date() }
      })
    }

    return { success: true }
  } catch (error) {
    console.error('Error in onUserLeftTeam:', error)
    return { success: false, error: 'Failed to remove user from department channel' }
  }
}

/**
 * Called when a leave request is approved - creates notification
 */
export async function onLeaveApproved(leaveRequestId: string) {
  try {
    const leaveRequest = await prisma.leaveRequest.findUnique({
      where: { id: leaveRequestId },
      include: {
        employee: {
          include: { user: true }
        }
      }
    })

    if (!leaveRequest) return { success: false, error: 'Leave request not found' }

    // Create notification for the employee
    await prisma.notification.create({
      data: {
        userId: leaveRequest.employee.userId,
        type: 'SYSTEM',
        title: 'Leave Request Approved',
        content: `Your leave request from ${leaveRequest.startDate.toDateString()} to ${leaveRequest.endDate.toDateString()} has been approved.`,
        actionUrl: '/dashboard/leave'
      }
    })

    return { success: true }
  } catch (error) {
    console.error('Error in onLeaveApproved:', error)
    return { success: false, error: 'Failed to create leave approval notification' }
  }
}

/**
 * Called when a task is assigned - creates notification
 */
export async function onTaskAssigned(taskId: string, assigneeId: string) {
  try {
    const task = await prisma.task.findUnique({
      where: { id: taskId },
      include: {
        createdBy: {
          select: { name: true, firstName: true, lastName: true }
        }
      }
    })

    if (!task) return { success: false, error: 'Task not found' }

    const creatorName = task.createdBy?.name || 
                       `${task.createdBy?.firstName} ${task.createdBy?.lastName}`.trim() || 
                       'Someone'

    await prisma.notification.create({
      data: {
        userId: assigneeId,
        type: 'TASK_ASSIGNED',
        title: 'New Task Assigned',
        content: `${creatorName} assigned you a new task: ${task.title}`,
        actionUrl: `/dashboard/tasks?task=${taskId}`,
        data: JSON.stringify({
          taskId,
          taskTitle: task.title,
          assignedBy: task.createdById
        })
      }
    })

    return { success: true }
  } catch (error) {
    console.error('Error in onTaskAssigned:', error)
    return { success: false, error: 'Failed to create task assignment notification' }
  }
}

/**
 * Export all sync functions for easy import
 */
export const CommunicationSync = {
  onUserApproved,
  onUserRewarded,
  onProjectStatusChange,
  onTeamCreated,
  onUserJoinedTeam,
  onUserLeftTeam,
  onLeaveApproved,
  onTaskAssigned
}