import { prisma } from "@/lib/db"

/**
 * Auto-generate department channels for teams
 */
export async function createDepartmentChannels() {
  try {
    // Get all active teams/departments
    const teams = await prisma.team.findMany({
      where: { isActive: true },
      include: {
        members: {
          where: { user: { status: 'ACTIVE' } },
          include: { user: true },
        },
      },
    })

    for (const team of teams) {
      // Check if department channel already exists
      const existingChannel = await prisma.chatChannel.findFirst({
        where: {
          type: 'DEPARTMENT',
          departmentId: team.id,
          isActive: true,
        },
      })

      if (!existingChannel && team.members.length > 0) {
        // Create department channel
        const channel = await prisma.chatChannel.create({
          data: {
            name: `${team.name} Team`,
            description: `Official channel for ${team.name} department`,
            type: 'DEPARTMENT',
            departmentId: team.id,
            isAutoGenerated: true,
            createdById: team.members[0].userId, // Use first member as creator
          },
        })

        // Add all team members to the channel
        const memberData = team.members.map(member => ({
          channelId: channel.id,
          userId: member.userId,
          role: member.role === 'LEADER' ? 'ADMIN' as const : 'MEMBER' as const,
        }))

        await prisma.chatMember.createMany({
          data: memberData,
        })

        // Send welcome message
        await prisma.chatMessage.create({
          data: {
            channelId: channel.id,
            authorId: team.members[0].userId,
            content: `Welcome to the ${team.name} team channel! 🎉 This is your space for team discussions, updates, and collaboration.`,
            messageType: 'SYSTEM',
          },
        })
      }
    }

    return { success: true, message: 'Department channels created successfully' }
  } catch (error) {
    console.error('Error creating department channels:', error)
    return { success: false, error: 'Failed to create department channels' }
  }
}

/**
 * Create announcement for new team member
 */
export async function createNewMemberAnnouncement(userId: string) {
  try {
    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: {
        firstName: true,
        lastName: true,
        name: true,
        department: true,
        jobTitle: true,
        avatar: true,
      },
    })

    if (!user) return { success: false, error: 'User not found' }

    // Find an admin to create the announcement
    const admin = await prisma.user.findFirst({
      where: {
        role: { in: ['SUPER_ADMIN', 'CEO', 'CFO', 'ADMIN', 'HR_OFFICER'] },
        status: 'ACTIVE',
      },
    })

    if (!admin) return { success: false, error: 'No admin found' }

    const displayName = user.name || `${user.firstName} ${user.lastName}`.trim()
    
    await prisma.announcement.create({
      data: {
        title: `Welcome ${displayName} to RYD! 🎉`,
        content: `Please join us in welcoming ${displayName} to the ${user.department || 'RYD'} team${user.jobTitle ? ` as ${user.jobTitle}` : ''}. We're excited to have you on board and look forward to working together!`,
        type: 'NEW_MEMBER',
        priority: 'NORMAL',
        isPublic: true,
        allowComments: true,
        allowReactions: true,
        isPublished: true,
        publishedAt: new Date(),
        authorId: admin.id,
        attachments: user.avatar ? JSON.stringify([{
          fileName: 'profile.jpg',
          fileUrl: user.avatar,
          fileType: 'image/jpeg',
        }]) : null,
      },
    })

    return { success: true, message: 'Welcome announcement created' }
  } catch (error) {
    console.error('Error creating new member announcement:', error)
    return { success: false, error: 'Failed to create announcement' }
  }
}

/**
 * Create announcement for user achievements/rewards
 */
export async function createAchievementAnnouncement(userId: string, badgeId: string, reason?: string) {
  try {
    const [user, badge] = await Promise.all([
      prisma.user.findUnique({
        where: { id: userId },
        select: {
          firstName: true,
          lastName: true,
          name: true,
          department: true,
          avatar: true,
        },
      }),
      prisma.rewardBadge.findUnique({
        where: { id: badgeId },
        select: {
          name: true,
          description: true,
          icon: true,
          color: true,
        },
      }),
    ])

    if (!user || !badge) return { success: false, error: 'User or badge not found' }

    // Find an admin to create the announcement
    const admin = await prisma.user.findFirst({
      where: {
        role: { in: ['SUPER_ADMIN', 'CEO', 'CFO', 'ADMIN', 'HR_OFFICER'] },
        status: 'ACTIVE',
      },
    })

    if (!admin) return { success: false, error: 'No admin found' }

    const displayName = user.name || `${user.firstName} ${user.lastName}`.trim()
    
    await prisma.announcement.create({
      data: {
        title: `🎉 ${displayName} earned "${badge.name}"!`,
        content: `Congratulations to ${displayName} from ${user.department || 'RYD'} for earning the "${badge.name}" badge! ${badge.description || ''}${reason ? ` Reason: ${reason}` : ''} Keep up the excellent work! 🌟`,
        type: 'ACHIEVEMENT',
        priority: 'NORMAL',
        isPublic: true,
        allowComments: true,
        allowReactions: true,
        isPublished: true,
        publishedAt: new Date(),
        authorId: admin.id,
        tags: JSON.stringify(['achievement', 'recognition', badge.name.toLowerCase()]),
      },
    })

    return { success: true, message: 'Achievement announcement created' }
  } catch (error) {
    console.error('Error creating achievement announcement:', error)
    return { success: false, error: 'Failed to create announcement' }
  }
}

/**
 * Create announcement for project updates
 */
export async function createProjectUpdateAnnouncement(projectId: string, updateType: 'STARTED' | 'COMPLETED' | 'MILESTONE') {
  try {
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        owner: {
          select: {
            firstName: true,
            lastName: true,
            name: true,
          },
        },
        projectLead: {
          select: {
            firstName: true,
            lastName: true,
            name: true,
          },
        },
      },
    })

    if (!project) return { success: false, error: 'Project not found' }

    const authorId = project.projectLeadId || project.ownerId
    let title = ''
    let content = ''

    switch (updateType) {
      case 'STARTED':
        title = `🚀 New Project: ${project.name}`
        content = `We're excited to announce the launch of "${project.name}"! ${project.description || ''} Led by ${project.projectLead?.name || project.owner.name}.`
        break
      case 'COMPLETED':
        title = `✅ Project Completed: ${project.name}`
        content = `Great news! The "${project.name}" project has been successfully completed. Thank you to everyone who contributed to this achievement!`
        break
      case 'MILESTONE':
        title = `🎯 Milestone Reached: ${project.name}`
        content = `The "${project.name}" project has reached an important milestone. Keep up the great work, team!`
        break
    }

    await prisma.announcement.create({
      data: {
        title,
        content,
        type: 'PROJECT_UPDATE',
        priority: 'NORMAL',
        isPublic: true,
        allowComments: true,
        allowReactions: true,
        isPublished: true,
        publishedAt: new Date(),
        authorId,
        tags: JSON.stringify(['project', project.name.toLowerCase(), updateType.toLowerCase()]),
      },
    })

    return { success: true, message: 'Project update announcement created' }
  } catch (error) {
    console.error('Error creating project update announcement:', error)
    return { success: false, error: 'Failed to create announcement' }
  }
}

/**
 * Create birthday announcements
 */
export async function createBirthdayAnnouncements() {
  try {
    const today = new Date()
    const todayMonth = today.getMonth() + 1
    const todayDate = today.getDate()

    // Find users with birthdays today
    const birthdayUsers = await prisma.user.findMany({
      where: {
        status: 'ACTIVE',
        employeeProfile: {
          dateOfBirth: {
            not: null,
          },
        },
      },
      include: {
        employeeProfile: {
          select: {
            dateOfBirth: true,
          },
        },
      },
    })

    const todaysBirthdays = birthdayUsers.filter(user => {
      if (!user.employeeProfile?.dateOfBirth) return false
      const birthDate = new Date(user.employeeProfile.dateOfBirth)
      return birthDate.getMonth() + 1 === todayMonth && birthDate.getDate() === todayDate
    })

    if (todaysBirthdays.length === 0) {
      return { success: true, message: 'No birthdays today' }
    }

    // Find an admin to create the announcement
    const admin = await prisma.user.findFirst({
      where: {
        role: { in: ['SUPER_ADMIN', 'CEO', 'CFO', 'ADMIN', 'HR_OFFICER'] },
        status: 'ACTIVE',
      },
    })

    if (!admin) return { success: false, error: 'No admin found' }

    for (const user of todaysBirthdays) {
      const displayName = user.name || `${user.firstName} ${user.lastName}`.trim()
      
      await prisma.announcement.create({
        data: {
          title: `🎂 Happy Birthday ${displayName}! 🎉`,
          content: `Join us in wishing ${displayName} from ${user.department || 'RYD'} a very happy birthday! Hope you have a wonderful day filled with joy and celebration! 🎈🎁`,
          type: 'BIRTHDAY',
          priority: 'NORMAL',
          isPublic: true,
          allowComments: true,
          allowReactions: true,
          isPublished: true,
          publishedAt: new Date(),
          authorId: admin.id,
          tags: JSON.stringify(['birthday', 'celebration']),
          expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // Expire after 24 hours
        },
      })
    }

    return { success: true, message: `Created ${todaysBirthdays.length} birthday announcements` }
  } catch (error) {
    console.error('Error creating birthday announcements:', error)
    return { success: false, error: 'Failed to create birthday announcements' }
  }
}

/**
 * Clean up expired announcements and old messages
 */
export async function cleanupCommunicationData() {
  try {
    const now = new Date()
    
    // Unpublish expired announcements
    await prisma.announcement.updateMany({
      where: {
        expiresAt: { lt: now },
        isPublished: true,
      },
      data: {
        isPublished: false,
      },
    })

    // Unpin expired pinned announcements
    await prisma.announcement.updateMany({
      where: {
        pinnedUntil: { lt: now },
        isPinned: true,
      },
      data: {
        isPinned: false,
        pinnedUntil: null,
      },
    })

    // Delete old notifications (older than 30 days)
    const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
    await prisma.notification.deleteMany({
      where: {
        createdAt: { lt: thirtyDaysAgo },
        isRead: true,
      },
    })

    // Archive old bulletin posts (older than 30 days and not pinned)
    await prisma.bulletinPost.updateMany({
      where: {
        createdAt: { lt: thirtyDaysAgo },
        isPinned: false,
        isPublished: true,
      },
      data: {
        isPublished: false,
      },
    })

    return { success: true, message: 'Communication data cleaned up successfully' }
  } catch (error) {
    console.error('Error cleaning up communication data:', error)
    return { success: false, error: 'Failed to clean up communication data' }
  }
}