name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Verify auth config (dev defaults)
        env:
          AUTH_SECRET: development-secret-change-in-production
          NEXTAUTH_URL: http://localhost:3000
          NODE_ENV: development
        run: npm run verify:auth
      - name: Build
        env:
          AUTH_SECRET: development-secret-change-in-production
          NEXTAUTH_URL: http://localhost:3000
          DATABASE_URL: postgresql://user:pass@localhost:5432/db?schema=public
          NODE_ENV: development
        run: npm run build --if-present